### ISSUE TITLE
User data?

### ISSUE THREAD

**Issue by HughP** [lcosmin/boardgamegeek#23]
I was looking at the documentation, and it seems that there are no options for user data via this library. http://lcosmin.github.io/boardgamegeek/modules.html#module-boardgamegeek.user Is this true? or is this just a fluke of the documentation? I interested in playing with user data, but need a tool to access it. I started messing around with this tool some weeks ago when I was looking at game data.

**Comment by lcosmin** [comment]
Meh. Yes, something should have been there. Documentation for this library has always been an work in progress... :( I'll make sure it's fixed in the refactored version (which I'm slooowly working on).

But I believe it's pretty easy to figure out even without the documentation. Just fire up an interactive Python and do something like:

    >>> from boardgamegeek import BoardGameGeek
    >>> bgg = BoardGameGeek()
    >>> u = bgg.user("fagentu007")
    >>> dir(u)
    ['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_buddies', '_data', '_format', '_guilds', '_hot', '_top', 'add_buddy', 'add_guild', 'add_hot_item', 'add_top_item', 'avatar', 'buddies', 'country', 'data', 'firstname', 'guilds', 'homepage', 'hot10', 'id', 'last_login', 'lastname', 'name', 'psn_account', 'state', 'steam_account', 'top10', 'total_buddies', 'total_guilds', 'trade_rating', 'wii_account', 'xbox_account']

You can see the properties of the User object here: https://github.com/lcosmin/boardgamegeek/blob/master/boardgamegeek/user.py#L117

I'll close this because of already having issue #8.
